[dependencies]
"wasmer/winterjs" = "*"

[fs]
"/web" = "dist"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--mode", "cloudflare", "/web"]
